# Generated by Django 5.0.2 on 2024-02-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='categoris'),
        ),
    ]
