# Generated by Django 5.0.2 on 2024-02-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_subcategory_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',), 'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
    ]
