# Generated by Django 5.0.2 on 2024-02-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('banner', models.ImageField(blank=True, upload_to='ads')),
                ('banner_2', models.ImageField(blank=True, upload_to='ads')),
                ('banner_3', models.ImageField(blank=True, upload_to='ads')),
                ('banner_4', models.ImageField(blank=True, upload_to='ads')),
                ('banner_5', models.ImageField(blank=True, upload_to='ads')),
                ('banner_6', models.ImageField(blank=True, upload_to='ads')),
                ('desc', models.TextField(blank=True)),
                ('desc_2', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ads',
                'verbose_name_plural': 'Ads',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='design_2image',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='design_2price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_1kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_2kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
