# Generated by Django 5.0.2 on 2024-02-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_ads_product_design_2image_product_design_2price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='desc_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='desc_4',
            field=models.TextField(blank=True),
        ),
    ]
