# Generated by Django 5.0.2 on 2024-03-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
